feat(stress): add `chain_id` to logs during funding (#1196)
Errors such as
```
[2m2025-08-20T17:40:10.804642Z[0m [32m INFO[0m [2mstress[0m[2m:[0m Funding accounts #0..1/1 on chain 42161
[2m2025-08-20T17:40:10.915252Z[0m [32m INFO[0m [2mstress[0m[2m:[0m Funding accounts #0..1/1 on chain 56
[2m2025-08-20T17:40:10.915826Z[0m [32m INFO[0m [2mstress[0m[2m:[0m Approving Disperse contract on chain 137 for token 0xc2132D05D31c914a87C6611C10748AEb04B58e8F
[2m2025-08-20T17:40:10.959493Z[0m [32m INFO[0m [2mstress[0m[2m:[0m Funding accounts #0..1/1 on chain 10
Error: server returned an error response: error code 3: execution reverted: ERC20: transfer amount exceeds balance, data: "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000"

Location:
    src/bin/stress.rs:403:25
```
can be hard to debug, because it's not clear on what chain the funding
has failed.