fix(metrics): tolerate same-block inclusion (#1272)
One of the tests in
https://github.com/ithacaxyz/relay/actions/runs/17304620512/job/49124276461

failed with:
```
    thread 'tokio-runtime-worker' panicked at src/transactions/signer.rs:827:30:
    attempt to subtract with overflow
```

which was this inclusion calculation code, meaning the submitted and
included block were calculated to be the same. Just using saturating sub
for now to prevent the panic